{% set data = load_setup_py_data() %}
{% set name = "seamm-installer" %}

package:
  name: "{{ data.get('name')|lower }}"
  version: "{{ data.get('version') }}"

source:
  # git_rev: {{ version }}
  # git_url: https://github.com/molssi-seamm/seamm_installer.git
  path: ../

build:
  noarch: python

requirements:
  build:
    - python
    - requests
    - setuptools
    - tabulate

  run:
    - python
    - requests
    - tabulate

test:
  imports:
    # - seamm-installer

about:
  home: {{ data.get('url') }}
  license:  {{ data.get('license') }}
  summary:  {{ data.get('description') }}
