name: Conda

on:
  push:
    branches:
      - "main"
  pull_request:
    branches:
      - "main"

jobs:
  lint:
    name: Lint ubuntu-latest Py3.8
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: Additional info about the build
      shell: bash
      run: |
        uname -a
        df -h
        ulimit -a
    # More info on options: https://github.com/conda-incubator/setup-miniconda
    - uses: conda-incubator/setup-miniconda@v2
      with:
        python-version: 3.8
        environment-file: conda_recipes/build_env.yaml
        activate-environment: test
        auto-update-conda: false
        auto-activate-base: false
        show-channel-urls: true
    - name: Create conda package
      # conda setup requires this special shell
      shell: bash -l {0}
      run: |
        mkdir ~/conda-bld
        export CONDA_BLD_PATH=~/conda-bld
        conda-build --no-anaconda-upload conda_recipes/
        ls -l conda_recipes
        ls -l ~/conda-bld
        anaconda -t ${{ secrets.ANACONDA_TOKEN }} upload -u seamm ~/conda-bld/* 
