# GitHub Actions for creating the documentation.
#    Thus runs on Linux only.

name: Documentation

on:
  push:
    branches-ignore:
      - 'main'
  release:
    types: [published]
    branches:
      - "main"

jobs:
  docs:
    name: Docs ubuntu-latest Py3.8
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
      with:
        # This gets all branches (1 = only current branch)
        fetch-depth: 0
    - name: Additional info about the build
      shell: bash
      run: |
        uname -a
        df -h
        ulimit -a
    # More info on options: https://github.com/conda-incubator/setup-miniconda
    - uses: conda-incubator/setup-miniconda@v2
      with:
        python-version: 3.8
        environment-file: devtools/conda-envs/docs.yaml
        activate-environment: docs
        auto-update-conda: false
        auto-activate-base: false
        show-channel-urls: true
    - name: Install package
      # conda setup requires this special shell
      shell: bash -l {0}
      run: |
        python -m pip install . --no-deps
        conda list
    - name: Build documentation
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      shell: bash -l {0}
      run: |
        devtools/scripts/buildDocs.sh
